# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'HelloOpenGLES' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HelloOpenGLES
  pod 'AHEasing',:git=>'https://github.com/warrenm/AHEasing.git',:tag=>'1.3.1'

end
